version: "3.9"

services:

  fullnode:
    build:
      context: ../..
      dockerfile: ./docker/sui-node/Dockerfile
      args:
        # update with git sha of whichever branch you're building on.
        GIT_REVISION: db24658bc9
        BUILD_DATE: today

    environment:
      - LD_PRELOAD
      - RUST_JSON_LOG="true"
      - RUST_LOG="info"
      # don't use debug, it generates volumes of data.
    image: sui-node:latest
    command: /opt/sui/entry.sh
    restart: unless-stopped
    # populate your local ./fullnode/config/ directory with fullnode.yaml and genesis.blob for the network you want to use.
    volumes:
      - ./fullnode:/opt/sui
    ports:
      - 9000
      - 9184
      - target: 8084
        published: 8084
        protocol: udp

  indexer:
    build:
      context: ../..
      dockerfile: ./docker/sui-indexer/Dockerfile
    image: sui-indexer:latest
    command: /opt/sui/indexer.sh
    restart: unless-stopped
    volumes:
      - ./indexer:/opt/sui
    environment:
      - RUST_LOG="info"
      - RUST_JSON_LOG="true"
      - DATABASE_URL=postgres://postgres:wKrepVoFdhali70iwHl4@sui-db.cnecsg0emuow.us-east-1.rds.amazonaws.com:5432/sui_indexer_mainnet
      - RPC_CLIENT_URL=http://fullnode:9000
    ports:
      - target: 9000
        published: 9001
        protocol: tcp
      - target: 9184
        published: 9185
        protocol: tcp 
    depends_on:
      - fullnode
